# Generated by Django 3.2.6 on 2021-09-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0002_rename_messages_comment_messaages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='messaages',
            new_name='messaage',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='users',
            new_name='uuser',
        ),
    ]
